# Generated by Django 4.1.5 on 2023-02-14 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.PROTECT, related_name='airline_code', to='flights.flight')),
                ('airline_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airline_name', to='flights.flight')),
            ],
        ),
    ]
