# Generated by Django 4.1.5 on 2023-03-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='airline_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='airline',
            name='airline_name',
            field=models.CharField(max_length=20),
        ),
    ]
