# Generated by Django 4.1.7 on 2023-03-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_airline_airline_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='airline_code',
            field=models.CharField(max_length=2),
        ),
    ]
